version: 2

jobs:
  build:
    docker:
    - image: circleci/php:7.1-fpm-node

    working_directory: ~/php_increments

    environment:
      TZ: "/usr/share/zoneinfo/Asia/Toyko"

    steps:
    - checkout

    - run: sudo composer self-update

    - run: echo 127.0.0.1 localhost | sudo tee -a /etc/hosts

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
        - v1-dependencies-

    - run: composer install -n --prefer-dist

    - save_cache:
        paths:
        - ./vendor
        key: v1-dependencies-{{ checksum "composer.json" }}

    - run: ./vendor/bin/phpunit