version: '3'

volumes:
  logs:
    driver: local

services:
  web:
    image: nginx:1
    ports:
    - "8080:80"
    links:
    - app
    volumes:
    - ./web/default.conf:/etc/nginx/conf.d/default.conf
    - ../.:/var/www/html

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      docker: "true"
    volumes:
    - ../.:/var/www/html